// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDWJxw50bz8EbdNqyWbNTtYtpM8O03Rw',
    appId: '1:1006537564588:web:7e79d65e4bdd6f38a4da09',
    messagingSenderId: '1006537564588',
    projectId: 'cart-5583b',
    authDomain: 'cart-5583b.firebaseapp.com',
    storageBucket: 'cart-5583b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPv8_Wj7Z32R3e1X2HiiLccPpdnGsGxw',
    appId: '1:1006537564588:android:563a6a04832758ffa4da09',
    messagingSenderId: '1006537564588',
    projectId: 'cart-5583b',
    storageBucket: 'cart-5583b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZJr0XMb2SCs1DFFWW3lvimoowzWRPYw',
    appId: '1:1006537564588:ios:9fa90786b683436fa4da09',
    messagingSenderId: '1006537564588',
    projectId: 'cart-5583b',
    storageBucket: 'cart-5583b.appspot.com',
    iosClientId: '1006537564588-6na62fcfqvgsc5sb2s19npvfmi60pslv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZJr0XMb2SCs1DFFWW3lvimoowzWRPYw',
    appId: '1:1006537564588:ios:9fa90786b683436fa4da09',
    messagingSenderId: '1006537564588',
    projectId: 'cart-5583b',
    storageBucket: 'cart-5583b.appspot.com',
    iosClientId: '1006537564588-6na62fcfqvgsc5sb2s19npvfmi60pslv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cart',
  );
}
